### 新增文章
POST http://localhost:3000/posts
Content-Type: application/x-www-form-urlencoded

{
  "title": "post title",
  "body": "post a new post from the test.http",
  "description": "description",
  "published": true
}


### 获取所有文章
GET http://localhost:3000/posts
Content-Type: application/json


### 删除文章
DELETE http://localhost:3000/posts/2
Content-Type: application/json

{
    "id":"1"
}


### 修改文章
PATCH http://localhost:3000/posts/1
Content-Type: application/json

{
    "published": false
}
